version: '3'
services:
  db:
    container_name: "bookstore-mysql"
    image: mysql/mysql-server:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore
    volumes:
      - ./docker/db:/var/lib/mysql